### ISSUE TITLE
Exception has occurred: RuntimeError CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by Wjt-shift** [yitongx/sinerf#2]
Thanks for your great work!when I run your code but meet some problem.
I find in your code.you initialize pose parameters as zeros.
`self.r=nn.Parameter(torch.zeros(size=(num_cams, 3), dtype=torch.float32), requires_grad=learn_R)`
the rotation set to zero.but when run _function_ `Exp(r)`,will compute and divide norm_r.In the first iter,the norm_r will be zero.Should I change the initialize pose parameters?
```
def Exp(r):
    """so(3) vector to SO(3) matrix
    :param r: (3, ) axis-angle, torch tensor
    :return:  (3, 3)
    """
    skew_r = vec2skew(r)  # (3, 3)
    norm_r = r.norm() + 1e-15
    print("r:",r)
    print("norm_r:",norm_r)
    eye = torch.eye(3, dtype=torch.float32, device=r.device)
    R = eye + (torch.sin(norm_r) / norm_r) * skew_r + ((1 - torch.cos(norm_r)) / norm_r**2) * (skew_r @ skew_r)
```

**Comment by yitongx** [comment]
Hi,

Thanks for your question!

Firstly, the pose parameters are indeed initialized as a zero vector. But as shown in the codes you posted below, there is a `1e-15` added to the `norm_r` to guarantee a reasonable division (namely line 67 in` utils/lie_group_helper.py`). In fact, I just followed NeRFmm's codes for initializing learnable extrinsic parameters and didn't make any modifications here. I think initializing pose parameters to other const vectors is okay as long as you don't induce any prior to the initialization.

Then, as to your error, I don't recall seeing any error like this when I ran either SiNeRF or NeRFmm's codes. This error looks like some problem with PyTorch to me. Maybe you can reinstall or try another version of torch-gpu and check your CUDA driver?

Best.

**Comment by Wjt-shift** [comment]
> 

Thanks for your quick reply!I have solved this problem by reinstall different torch version.Thanks for your advices!
